apiVersion: v1
kind: Service
metadata:
  name: gbook-live
spec:
  #  ClusterIP
  type: LoadBalancer
  selector:
    app: gbook-live
  ports:
    - protocol: TCP
      name: http
      port: 81
      targetPort: 8080